version: '2'
services:
  mysql:
      image: treenity/mysql
      environment:
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - "./.docker/database:/var/lib/mysql"
      ports:
        - "3306:3306"

  php:
      image: treenity/php:5.6
      links:
        - mysql
        - blackfire
        - maildev
      volumes:
        - "./:/var/www/html"
      environment:
        XDEBUG_ENABLE: 1
        XDEBUG_CONFIG: "remote_host=192.168.43.38"
        PHP_IDE_CONFIG: "serverName=docker"

  nginx:
      image: treenity/nginx
      restart: always
      ports:
        - "80:80"
        - "443:443"
        - "9000:9000"
      volumes_from:
        - php

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - mysql
      environment:
        PMA_HOST: mysql
        PMA_USER: root
        PMA_PASSWORD: root
      restart: always
      ports:
        - "8080:80"
      volumes:
        - "/sessions"

  blackfire:
      image: blackfire/blackfire
      environment:
        BLACKFIRE_CLIENT_ID:
        BLACKFIRE_CLIENT_TOKEN:
        BLACKFIRE_SERVER_ID:
        BLACKFIRE_SERVER_TOKEN:

  maildev:
      image: djfarrelly/maildev
      ports:
        - "1080:80"
