version: '2'
services:
  webserver:
      build: ./nginx
      container_name: webserver
      volumes_from:
        - php-fpm
      ports:
        - "80:80"
      links:
        - php-fpm

  php-fpm:
      build: ./fpm/5.6
      container_name: php-fpm
      volumes:
        - ./:/var/www/html
      environment:
        XDEBUG_CONFIG: "remote_host=192.168.1.10 remote_enable=0 profiler_enable=0"
        PHP_IDE_CONFIG: "serverName=docker"