version: '2'
services:
  data:
    image: busybox:latest
    volumes:
      - "./.docker/database:/var/lib/mysql"
      - "./:/app"
    command: /bin/echo

  mysql:
      build: mysql
      environment:
        MYSQL_DATABASE: bac45
        MYSQL_USER: bac45
        MYSQL_PASSWORD: bac45
        MYSQL_ROOT_PASSWORD: root
      volumes_from:
        - data
      ports:
        - 3306:3306

  php:
      build: fpm/5.6
      links:
        - mysql
        - blackfire
        - maildev
      volumes_from:
        - data
      environment:
        XDEBUG_ENABLE: 0
        OPCACHE_ENABLE: 0
        XDEBUG_CONFIG: "remote_host=192.168.1.10"
        PHP_IDE_CONFIG: "serverName=docker"

  nginx:
      build: nginx
      restart: always
      ports:
        - "80:80"
      volumes_from:
        - data

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - mysql
      environment:
        - PMA_HOST=mysql
        - PMA_USER=root
        - PMA_PASSWORD=root
      restart: always
      ports:
        - "8080:80"
      volumes:
        - "/sessions"

  blackfire:
      image: blackfire/blackfire
      environment:
        BLACKFIRE_CLIENT_ID: ***
        BLACKFIRE_CLIENT_TOKEN: ***
        BLACKFIRE_SERVER_ID: ***
        BLACKFIRE_SERVER_TOKEN: ***

  maildev:
      image: djfarrelly/maildev
      ports:
        - "1080:80"
