version: '2'
services:
  mysql:
      image: treenity/mysql
      environment:
        MYSQL_DATABASE: ${PROJECT_NAME}
        MYSQL_USER: ${PROJECT_NAME}
        MYSQL_PASSWORD: ${PROJECT_NAME}
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - "mysql_datas:/var/lib/mysql"
      ports:
        - 3306:3306

  webserver:
#if ($USE_NGINX != '' && $USE_NGINX != 'n')
      image: treenity/nginx
#else
      image: treenity/apache
#end
      volumes_from:
        - php-fpm
      ports:
        - 80:80
        - 443:443
      environment:
        NGINX_HOST: 192.168.99.100
        NGINX_PORT: 80
      command: /bin/bash -c "envsubst '\\$$NGINX_HOST \\$$NGINX_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  php-fpm:
#if ($PHP_VERSION != '')
      image: treenity/php:$PHP_VERSION
#else
      image: treenity/php:7.0
#end
      volumes:
        - ./:/var/www/html
        #- ./.docker/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini
      ports:
        - 9000:9000
      environment:
        XDEBUG_CONFIG: "#if($XDEBUG_IP != '')remote_host=$XDEBUG_IP#end#if($USE_XDEBUG != '' && $USE_XDEBUG != 'n') remote_enable=1#end#if($USE_XDEBUG_PROFILER != '' && $USE_XDEBUG_PROFILER != 'n') profiler_enable=1#end"
        PHP_IDE_CONFIG: "serverName=docker"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - mysql
      environment:
        PMA_HOST: mysql
        PMA_USER: root
        PMA_PASSWORD: root
      restart: always
      ports:
        - 8080:80

  memcached:
      image: memcached:latest

  mailhog:
      image: mailhog/mailhog:latest
      ports:
        - 8081:8025

  dockerui:
      image: uifd/ui-for-docker
      restart: always
      privileged: true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 8082:9000

#if ($USE_BLACKFIRE != '' && $USE_BLACKFIRE != 'n')
  blackfire:
    image: blackfire/blackfire
    environment:
      BLACKFIRE_CLIENT_ID: YOUR_BLACKFIRE_CLIENT_ID
      BLACKFIRE_CLIENT_TOKEN: YOUR_BLACKFIRE_CLIENT_TOKEN
      BLACKFIRE_SERVER_ID: YOUR_BLACKFIRE_SERVER_ID
      BLACKFIRE_SERVER_TOKEN: YOUR_BLACKFIRE_SERVER_TOKEN

#end
volumes:
  mysql_datas:
    driver: local
