version: '2'
services:
  memcached:
      image: memcached:latest
      container_name: memcached

  mysql:
    image: treenity/mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - "./docker/mysql/database:/var/lib/mysql"

  apache:
    image: treenity/apache
    container_name: apache
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
      - memcached:memcached
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html"
    environment:
      XDEBUG_CONFIG: "remote_host={{YOUR_LOCAL_IP]]"
      PHP_IDE_CONFIG: "serverName={{DOCKER_HOST_IP}}"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    restart: always
    ports:
      - 8080:80
    volumes:
      - "/sessions"
