#set($DOLLAR = '$')
version: '2'
services:
  mysql:
      image: treenity/mysql
      environment:
        MYSQL_DATABASE: ${PROJECT_NAME}
        MYSQL_USER: ${PROJECT_NAME}
        MYSQL_PASSWORD: ${PROJECT_NAME}
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - "mysql_datas:/var/lib/mysql"
      ports:
        - 3306:3306

  webserver:
#if ($USE_NGINX != '' && $USE_NGINX != 'n')
      image: treenity/nginx
#else
      image: treenity/apache
#end
      volumes_from:
        - php-fpm
      ports:
#if ($NGINX_PORT != '')
        - $NGINX_PORT:80
#else
        - 80:80
#end
      environment:
#if ($NGINX_HOST != '')
        NGINX_HOST: $NGINX_HOST
#else
        NGINX_HOST: 192.168.99.100
#end
#if ($NGINX_PORT != '')
        NGINX_PORT: $NGINX_PORT
#else
        NGINX_PORT: 80
#end
      command: /bin/bash -c "envsubst '\\${DOLLAR}${DOLLAR}NGINX_HOST \\${DOLLAR}${DOLLAR}NGINX_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
      
  php-fpm:
#if ($PHP_VERSION != '')
      image: treenity/php:$PHP_VERSION
#else
      image: treenity/php:7.0
#end
      volumes:
        - ./:/var/www/html
        #- ./.docker/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini
      ports:
        - 9000:9000
      environment:
        XDEBUG_CONFIG: "#if($XDEBUG_IP != '')remote_host=$XDEBUG_IP#end#if($USE_XDEBUG != '' && $USE_XDEBUG != 'n') remote_enable=1#end#if($USE_XDEBUG_PROFILER != '' && $USE_XDEBUG_PROFILER != 'n') profiler_enable=1#end"
        PHP_IDE_CONFIG: "serverName=docker"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - mysql
      environment:
        PMA_HOST: mysql
        PMA_USER: root
        PMA_PASSWORD: root
      restart: always
      ports:
        - 8080:80

  memcached:
      image: memcached:latest

  mailhog:
      image: mailhog/mailhog:latest
      ports:
        - 8081:8025

  dockerui:
      image: uifd/ui-for-docker
      restart: always
      privileged: true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 8082:9000
        
#if ($USE_BLACKFIRE != '' && $USE_BLACKFIRE != 'n')
  blackfire:
      image: blackfire/blackfire
      environment:
        BLACKFIRE_CLIENT_ID: 74293842-4c71-4dd4-86e0-258f1c99b666
        BLACKFIRE_CLIENT_TOKEN: d9056ae4eb3480a1137e0fa593dc37f7da0bed77c7b86f50ec49f7dffd7a0a84
        BLACKFIRE_SERVER_ID: c4b3be3a-7aca-4c04-be7f-5005e7668fb5
        BLACKFIRE_SERVER_TOKEN: cff08d8f7d76145db92d164ac708c0ba1f9c0b173ff497768813ce01390dbcd1

#end
volumes:
  mysql_datas:
    driver: local
